### ISSUE TITLE
Add support for simplicial complexes

### ISSUE THREAD

**Issue by nwlandry** [ComplexGroupInteractions/xgi#1]
Because one can infer all the sub-interactions given a simplex, perhaps it is beneficial to store a simplicial complex using it's maximal edges to save space and perhaps use to develop efficient algorithms.

**Comment by leotrs** [comment]
Importantly, if we change the internal data structure, we would have to create an entirely new class (as opposed to inherit from `Hypergraph`). This is not necessarily a problem, but it will require rewriting essentially the entire interface.
