### ISSUE TITLE
Lazy View construction not working

### ISSUE THREAD

**Issue by nwlandry** [ComplexGroupInteractions/xgi#103]
When calling the `.nodes` property, cProfile indicates that every time that H.nodes is called, a new object is constructed (the hypergraph for which this profile was run has 2261 nodes):
![image](https://user-images.githubusercontent.com/8760347/165805373-0119f2c1-be9d-4e5d-9a15-b6d0cfb79ec2.png)
This shouldn't happen with the Lazy View construction. The same thing happens with calling `H.edges`

**Comment by nwlandry** [comment]
NetworkX seems to have similar behavior
<img width="554" alt="image" src="https://user-images.githubusercontent.com/8760347/166503139-e258f3ff-4b17-4dc9-92b3-35cdb99a43b1.png">
where the constructor is called every time `G.nodes[n]` is accessed.

**Comment by nwlandry** [comment]
@jarodmillman, I was wondering if this is expected "lazy view creation" behavior. I expected that the constructor for the `NodeView` class would get called once and then get overloaded so that the constructor wouldn't be called again, which doesn't seem to be the case. Thanks!

**Comment by stefanv** [comment]
Verified:

```
In [1]: import networkx as nx
   ...: 
   ...: G = nx.lollipop_graph(4, 6)

In [2]: x = G.nodes

In [3]: id(x)
Out[3]: 139952147798464

In [4]: y = G.nodes

In [5]: id(y)
Out[5]: 139952129631920
```

**Comment by stefanv** [comment]
Explanation: https://stackoverflow.com/q/48717893
