### ISSUE TITLE
Allow the colors parameters in the `draw` function to accept dictionary or array of colors

### ISSUE THREAD

**Issue by mcontisc** [ComplexGroupInteractions/xgi#138]
So far, the colors parameters in the `draw` function accept only one string value. However, I would find useful to have the same format as the networkx function where a practitioner can specify ideally a different color for every node/edge.

**Comment by leotrs** [comment]
Hi Martina! Thank you very much for reporting this issue. You are right, this would be a desirable feature. Let me take a look!

**Comment by leotrs** [comment]
@mcontisc please check out PR #139! Let me know if the image below looks like what you had in mind. 
![2022-07-20-084651_1518x633_scrot](https://user-images.githubusercontent.com/1096704/179915519-cb23b475-7121-40d0-b1ff-e2112272e612.png)

**Comment by leotrs** [comment]
@mcontisc Thanks for opening this issue. It has now been implemented. 

We are always looking for collaborators, so please feel free to keep opening issues, or better yet, joining us in our Zulip channel you can find [here](https://xgi.readthedocs.io/en/latest/about.html#contributing).

**Comment by mcontisc** [comment]
Thank you for the timely and friendly support :) 
I will keep an eye on the library and have in mind the channel.
