### ISSUE TITLE
How to compute the second moment of a NodeStat?

### ISSUE THREAD

**Issue by leotrs** [ComplexGroupInteractions/xgi#149]
Currently we have `H.nodes.degree.mean()` and `H.nodes.degree.std()`, but we should also have a convenience method to compute the second moment (centered or uncentered) since this is so important in network science.

**Comment by nwlandry** [comment]
I was thinking about this and could we have a `power` keyword? In my work, I've regularly dealt with 3rd moments

**Comment by leotrs** [comment]
I was thinking about something like
```python3
H.nodes.degree.moment(order, center)
```
with the default being
```python3
H.nodes.degree.moment(order=2, center=False)
```
I think "order" is better than "power" as it's used for example in the [Wikipedia](https://en.wikipedia.org/wiki/Moment_(mathematics)) article.
