### ISSUE TITLE
Add unit tests for XGI

### ISSUE THREAD

**Issue by nwlandry** [ComplexGroupInteractions/xgi#18]
Write initial tests for XGI using pytest for the following files:

- [x] algorithms/connected.py
- [x] classes/function.py
- [ ] classes/hypergraph.py
- [x] classes/hypergraphviews.py
- [ ] classes/reportviews.py
- [x] generators/classic.py
- [ ] generators/nonuniform.py
- [x] generators/uniform.py
- [x] linalg/matrix.py
- [x] readwrite/bipartite.py
- [x] readwrite/edgelist.py
- [x] readwrite/incidence_matrix.py
- [x] readwrite/json.py
- [ ] utils/utilities.py
- [ ] convert.py

**Comment by leotrs** [comment]
We have tons of tests now and we are keeping track of them using codecov, so I think this issue has ran its course.
