### ISSUE TITLE
Fix Github action for unit tests

### ISSUE THREAD

**Issue by nwlandry** [ComplexGroupInteractions/xgi#19]
The .github/workflows/test.yml file needs to be edited so that the tests pass. I removed doctests for now. Having trouble getting it to work so would appreciate any help.

**Comment by nwlandry** [comment]
<img width="329" alt="image" src="https://user-images.githubusercontent.com/8760347/145283137-74b42b32-b322-4e60-bef1-aad7f9d84eeb.png">
This is the error message, which seems to indicate that it will be fixed once there are some unit tests.

**Comment by leotrs** [comment]
[Logs here](https://github.com/ComplexGroupInteractions/xgi/runs/4452117017?check_suite_focus=true).

You're right, this will go away once we have tests.
