### ISSUE TITLE
Wrong constructor used in clear_edges() 

### ISSUE THREAD

**Issue by tomcjackc** [ComplexGroupInteractions/xgi#198]
On line 885 of hypergraph.py, the wrong constructor is used when resetting the nodes during the action of the clear_edges() method. The dict constructor (`{}`) is used when it should be the set constructor (`set()`). This means that an error is raised when trying to add edges back after clearing all edges. 

Error raised: `AttributeError: 'dict' object has no attribute 'add'`

This can be rectified by replacing the `{}` with `set()` on line 885.

**Comment by leotrs** [comment]
Hello @tomcjackc and thank you very much for filing this issue and suggesting a solution. I have made a new PR #199 addressing this.

Please feel free to open any more issues as you encounter them! Thanks for contributing to XGI.
