### ISSUE TITLE
Better way of getting node and edge data

### ISSUE THREAD

**Issue by nwlandry** [ComplexGroupInteractions/xgi#20]
Currently the way of accessing nodal data of node 1 is `H.nodes.data()[1]` or `H.nodes(1).data()` and a more streamlined call would be preferable. Currently `.nodes(id)` and `.nodes[id]` access a node's bipartite neighbors so this probably is an undesirable way of doing it. The problem is that unlike NetworkX, we are using two dictionaries each for nodes and edges: one for nodes and one for attributes. So, I'm not sure what the function would return. I see three options 1) a separate property of `Hypergraph` called `H.node_data` or something 2) a flag `data` where if `data=True`, then it returns the node attributes and if false, it returns the nodes with the bipartite connections, or 3) return a tuple of the bipartite connections and data respectively. Would appreciate your thoughts!

**Comment by leotrs** [comment]
I highly prefer a single way of doing things, so I would add to this issue that among the two calls
```python
H.nodes.data()[1]
H.nodes(1).data()
```
we choose one and remove the other. If we implement something entirely new, then I would suggest keeping the new one and removing these two (if possible).


> 2) a flag data where if data=True, then it returns the node attributes and if false, it returns the nodes with the bipartite connections
> 3) return a tuple of the bipartite connections and data respectively.

If I understood correctly, these two suggestion propose to return both the neighbors and the data at the same time. I think this may be a bit confusing, so I would vote for suggestion 1).

**Comment by leotrs** [comment]
We can currently get the node and edge data via `H.nodes[0]` and `H.edges[0]`.
