### ISSUE TITLE
bug: add_edge removes other edge

### ISSUE THREAD

**Issue by maximelucas** [ComplexGroupInteractions/xgi#224]
Create a Hypergraph:
```python
import xgi
H = xgi.Hypergraph({0: {1, 2}, 1: {1, 4}, 
                     2: {0, 1, 8}, 3: {0, 3, 5}})
H._edge
# -> {0: {1, 2}, 1: {1, 4}, 2: {0, 1, 8}, 3: {0, 3, 5}} # all fine
```
Then remove an edge
```python
H.remove_edge(2)
H._edge
# -> {0: {1, 2}, 1: {1, 4}, 3: {0, 3, 5}} # all fine
```

But then, when adding a new hyperedge, [1,9,2], it is assigned the ID 0 already in use, and the previous hyperedge with ID 0 has disappeared:
```python
H.add_edge([1,9,2])
H._edge
# {0: {1, 2, 9}, 1: {1, 4}, 3: {0, 3, 5}} # wrong
```
It should just be assigned a new ID, probably 4. Not sure what is causing this yet.

Instead, specifying the ID explicitly works, and gives the expected result, but the above is still wrong:
```python
H.add_edge([1,9,2], id=4)
H._edge
# -> {0: {1, 2}, 1: {1, 4}, 3: {0, 3, 5}, 4: {1, 2, 9}} # correct
```

**Comment by maximelucas** [comment]
Exactly

```python
H = xgi.Hypergraph({0: {1, 2}, 1: {1, 4}, 2: {0, 1, 8}, 3: {0, 3, 5}})
H._edge_uid
# -> count(0) # wrong
```
But
```python
H = xgi.Hypergraph([{1, 2}, {1, 4}, {0, 1, 8}, {0, 3, 5}])
H._edge_uid
# -> count(4) # correct
```

**Comment by leotrs** [comment]
`convert_to_hypergraph` calls `H.add_edges_from` which in turn increments `_edge_uid` but ONLY when the `incoming_data` is a list. All other cases use different mechanisms to add the edges so count is not incremented.

**Comment by maximelucas** [comment]
Yep, my conclusion too.
