### ISSUE TITLE
add "reverse" keyword in the convert/read bipartite edgelist

### ISSUE THREAD

**Issue by nwlandry** [ComplexGroupInteractions/xgi#24]
The default behavior is that the first column specifies the nodes and the second column specifies the edges. Instead of calling this method and then `H.dual()`, it would be nice if there was `reverse=True` to switch the labels. This would affect the following functions:
* read_bipartite_edgelist()
* write_bipartite_edgelist()
* from_bipartite_pandas_dataframe()

**Comment by leotrs** [comment]
I'd suggest the flag is `dual=True` rather than `reverse=True`.
