### ISSUE TITLE
online docs: make both dev and stable available

### ISSUE THREAD

**Issue by maximelucas** [ComplexGroupInteractions/xgi#265]
Right now, the online docs correspond to the dev version present on branch main, not to the pipy version of XGI

**Comment by nwlandry** [comment]
Update to this is that I changed the default version in RTD to "stable" instead "latest", but both are available in the sidebar. Does this fix the issue?

**Comment by nwlandry** [comment]
![Screenshot_20230109_074317_Chrome](https://user-images.githubusercontent.com/8760347/211310985-c30617c3-2200-4672-8a02-2157abcd3356.jpg) a screenshot of what I mean
