### ISSUE TITLE
erdos_renyi_hypergraph() : does not have n nodes

### ISSUE THREAD

**Issue by maximelucas** [ComplexGroupInteractions/xgi#27]
As discussed today, trying the random hypergraph generator: 
```python
import xgi
n = 10
m = 100
p = 0.01
H = xgi.erdos_renyi_hypergraph(n, m, p)

H.nodes
# NodeView((1, 3, 6, 7, 9))
```
the hypergraph has 5 nodes, not 10, even though the doc says `n` is the number of nodes. 

This discrepancy between n and the actual number of nodes is apparently expected for small n and p (correct me if I'm wrong).
If so, add a warning to the docstring. Otherwise, fix the bug.

**Comment by leotrs** [comment]
I vote we always add the correct number of nodes, even if that creates isolates.

**Comment by iaciac** [comment]
This is what I have been doing when creating the starting links for a SC, but I know it's not the most elegant solutions:

```python
    #I first generate a standard ER graph with edges connected with probability p1
    G = nx.fast_gnp_random_graph(N, p1, seed=None)
    
    if not nx.is_connected(G):
        #giant = max(nx.connected_component_subgraphs(G), key=len) 
        # deprecated, replaced by:
        connected_components = (G.subgraph(c).copy() for c in nx.connected_components(G))
        giant = max(connected_components, key=len) 
        print(f"WARNING: Not connected, but GC has order {giant.order()}, and size {giant.size()}")
        G = giant
```

**Comment by leotrs** [comment]
I like the idea of issuing warnings whenever the library returns something unexpected.

**Comment by nwlandry** [comment]
I'm also in favor of adding isolates. Adding warnings is fine too, but even if there are no isolates, the hypergraph can be disconnected, so I think if we specify that the graph is not connected, we need to run the `is_connected` method.
