### ISSUE TITLE
Cannot install xgi

### ISSUE THREAD

**Issue by avecsally** [ComplexGroupInteractions/xgi#287]
Dear contributors, 

First of all, thank you so much for the hard work putting all these together. Amazing!
I tried to redo the tutorials, however, I found I cannot install the xgi package at all. How frustrating. 
After I pip installed the xgi package, if I go to the notebook and tried to import it, I got this error message that avoid me having the package imported: 
"ImportError: cannot import name 'csr_array' from 'scipy.sparse' (/opt/anaconda3/lib/python3.9/site-packages/scipy/sparse/__init__.py)"
It seems like something's going on with scipy when importing xgi. 
I really have no idea how to deal with this problem. 

I hope my question would be helpful for your debugging process and looking forward to hearing the solution!

Best wishes, 
Sally

**Comment by nwlandry** [comment]
Dear Sally, thanks so much for the feedback!! And sorry to hear that XGI isn't working. Could you confirm which versions of XGI and scipy you are running so I can better assist?

**Comment by iaciac** [comment]
Hello Sally, 
I believe the problem is that xgi now needs a version of scipy which is not the one listed in the requirements (that should be updated). Try to upgrade scipy to the latest version and give it another go ;)
Cheers,
Iac
