### ISSUE TITLE
misleading name of from_simplicial_complex_to_hypergraph()

### ISSUE THREAD

**Issue by maximelucas** [ComplexGroupInteractions/xgi#295]
The function returns a Hypergraph constructed from the maximal simplices of the provided simplicial complex. 
The name of the function makes hides the fact that only maximal simplices are kept.

**Comment by maximelucas** [comment]
The function lives here: https://github.com/ComplexGroupInteractions/xgi/blob/main/xgi/convert.py
We don't want the name to be confusing with respect to other function in that file.
Input of the function: a SimplicialComplex. Ouput: a Hypergraph containing the maximal simplices from the input.

What about `from_max_simplices`? (But the input is not "max simplices).
Other names I can think of are too long or more confusing.

**Comment by nwlandry** [comment]
I think that `from_max_simplices` sounds good. The only other thing I can think of is `from_simplicial_complex_to_maximal_hypergraph()` which I don't think is quite accurate.
