### ISSUE TITLE
Improve View object interface

### ISSUE THREAD

**Issue by leotrs** [ComplexGroupInteractions/xgi#30]
In networkx, the (only?) way to get the largest degree is the following:
```python
max(list(dict(G.degree()).values()))
```
I find this unacceptable. In `xgi`, I propose we implement something like the following:
```python
max(H.degree().values())
```
That is, we should try to give the View objects a bit of an interface that makes them behave like the object they point to. Specifically, since `H.degree()` returns a DegreeView, which looks like a dictionary,
```python
H.degree()
# -> DegreeView({0: 10, 1: 20, ...})
```
we should make the DegreeView object support some of the methods of a dictionary,
```python
H.degree().values()
# -> [10, 20]
```

**Comment by iaciac** [comment]
I agree that networkx's solution is mental. Regarding the different degree orders (that we will add to the degree function), how should we work with the max? Should we find all the maxima (one for each order) from the different degree sequences or should we simply have a function that directly returns the max degree at each order?

**Comment by leotrs** [comment]
Ah that's a good point... I guess we should also implement the following then, mirroring the interface proposed in [this comment](https://github.com/ComplexGroupInteractions/xgi/issues/5#issuecomment-934338908):
```python
H.max_degree()
# -> global max degree across all orders

H.max_degree(order=m)
# -> max degree of order m

H.max_degree(order={m1, m2, m3})
# -> dict {m1: max1, m2: max2, m3: max3}

H.max_degree(order={m1, m2, m3}, type=dict)
# -> same as above

H.max_degree(order={m1, m2, m3}, type=array)
# -> array [max1, max2, max3]
```
Am I overengineering this, or do people think this is reasonable?

**Comment by nwlandry** [comment]
I 100% agree that the interface needs to be better. Something that is an issue with the degree is that it is a property of `Hypergraph` but the constructor of DegreeView accepts nodes, weights, and now order and type. 

What I was picturing doing on this was to make the degree not a property and call the degrees in Hypergraph with all optional arguments. The only disadvantage to this approach is that you couldn't call `H.degree`; it would always be `H.degree()`.

**Comment by nwlandry** [comment]
A thought that I have about the internals of the DegreeView class: In NetworkX, they allow a user to use the `__call__()` and `__getitem__()` methods but those methods in turn call the constructor which seems overly complicated.

A thought that I have is to change `degree` from a property to a method in the Hypergraph class and potentially either (a) implement computing the degrees in the constructor or (b) delete the DegreeView class.

**Comment by nwlandry** [comment]
Did NodeStat/EdgeStat sufficiently address this? I'm inclined to close this issue, but what do you all think?
