### ISSUE TITLE
sparse warning in adjacency matrix

### ISSUE THREAD

**Issue by maximelucas** [ComplexGroupInteractions/xgi#302]
Running

```python
import xgi
H = xgi.load_xgi_data("email-enron", max_order=None)

I , _, _ = xgi.incidence_matrix(H, order=order, sparse=sparse, index=True) # I is csr_array
A = I.dot(I.T) # A is a csr_array
if sparse: # here sparse=True
    A.setdiag(0) # A is still a csr_array but a warning is thrown!
```
The last line setting the diagonal yields a warning:

```python
venv_xgi/lib/python3.9/site-packages/scipy/sparse/_index.py:146: SparseEfficiencyWarning: 
Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)
```

which mentions `csr_matrix` although A is a `csr_array`.

**Comment by maximelucas** [comment]
From Scipy: not everything is ported yet
https://docs.scipy.org/doc/scipy/reference/sparse.html
> The construction utilities ([eye](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.eye.html#scipy.sparse.eye), [kron](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.kron.html#scipy.sparse.kron), [random](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.random.html#scipy.sparse.random), [diags](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.diags.html#scipy.sparse.diags), etc.) have not yet been ported, but their results can be wrapped into arrays: `A = csr_array(eye(3))`

I think `setdiag` hasn't been ported yet either, it's listed as a method for `csr_array` but it points to source code for `csr_matrix` I think: https://github.com/scipy/scipy/blob/v1.10.1/scipy/sparse/_base.py#L1235-L1258

**Comment by maximelucas** [comment]
More importantly probably, with `setdiag` we are changing the entries of a `csr_array` which can be expensive apparently.

**Comment by nwlandry** [comment]
Okay, I think I figured this out. When there are isolated nodes in the hypergraph, the warning in `adjacency_matrix()` is triggered. When every node is associated to at least one edge (even singletons), no warning is raised.

**Comment by maximelucas** [comment]
Oh okay, thanks. How come?

**Comment by nwlandry** [comment]
Short answer: no idea. Longer answer is that in the `_compressed.py` file, this [line](https://github.com/scipy/scipy/blob/c1ed5ece8ffbf05356a22a8106affcd11bd3aee0/scipy/sparse/_compressed.py#L909) and the following check the matrix for consistency or something like that and if it isn't, the warning is raised. That being said, I don't know what those functions actually check. One thing that we could do is to wrap the warning with a more interpretable message.
