### ISSUE TITLE
Function to convert from hypergraph to a simplicial complex

### ISSUE THREAD

**Issue by nwlandry** [ComplexGroupInteractions/xgi#305]
The function would input a hypergraph, extract the maximal faces, and initialize a SimplicialComplex with these maximal faces.

**Comment by maximelucas** [comment]
We have one that takes an SC as input, and outputs a HG containing the maximal simplices from the SC.

**Comment by maximelucas** [comment]
But Nich, I think what you're suggesting can be achieved by simply doing:
`H = xgi.Hypergraph(S)`?

**Comment by maximelucas** [comment]
But Nich, can you no just do `S = xgi.SimplicialComplex(H)` to do this?

**Comment by maximelucas** [comment]
What about `S = xgi.SimplicialComplex(H._edge)`

**Comment by nwlandry** [comment]
I get `XGIError: Cannot generate SimplicialComplex from simplex dictionary` 😢

**Comment by nwlandry** [comment]
The only thing that works right now for me is `SC = xgi.SimplicialComplex(H.edges.members())`

**Comment by maximelucas** [comment]
> The only thing that works right now for me is `SC = xgi.SimplicialComplex(H.edges.members())`

Ah good. Is that you wanted?

>  I get` XGIError: Cannot generate SimplicialComplex from simplex dictionary` 😢

Ah yes true, we didn't implement that input format for SC. I don't remember if there was a reason or if we just didn't get round to it?

**Comment by nwlandry** [comment]
It's worth noting that `H = xgi.Hypergraph(SC)` works so it would be great to implement something similar

**Comment by maximelucas** [comment]
@nwlandry if I'm not mistaken we have a solution to the original issue but mentioned another idea about implementing more input types for the SC constructor, right?
If so, I'd close this issue and open a new one about that.

**Comment by nwlandry** [comment]
Good point. I'll do that.
