### ISSUE TITLE
clustering coefficient not 1 in all-to-all

### ISSUE THREAD

**Issue by maximelucas** [ComplexGroupInteractions/xgi#309]
I'm not sure we're using the definition we want to be using for the clustering coefficient. 
If we are, we should make its behaviour more explicit in the docs. 

Running:
```python
H = xgi.random_hypergraph(3, [1, 1]) # all edges, all triangles
H.clustering()
# --> {0: 0.333, 1: 0.333, 2: 0.333} # those are not 1!
```

yields values that are not 1 (the value I expected). Changing the number of nodes also changes the result. 

Note that having only edges does work:
```python
H = xgi.random_hypergraph(3, [1]) # all edges, no triangles
H.clustering()
# --> {0: 1, 1: 1, 2: 1} # ok
```
because we are using a definition that directly generalises the pairwise clustering coefficient.

**Comment by leotrs** [comment]
It sounds like we need a similar discussion as the one we had for density. (What is the right denominator?)
