### ISSUE TITLE
names of centrality measures

### ISSUE THREAD

**Issue by nwlandry** [ComplexGroupInteractions/xgi#317]
I was noticing that I named the functions `CEC_centrality` and `HEC_centrality`. But "CEC" is an acronym for "Clique motif Eigenvector Centrality" (Benson [2019](https://arxiv.org/pdf/1807.09644.pdf)) and "HEC" is an acronym for "H-eigenvector centrality" (Benson [2019](https://arxiv.org/pdf/1807.09644.pdf)) so "centrality" in the function names is redundant. Any ideas for renaming these?

**Comment by maximelucas** [comment]
Some options:
1. `CE_centrality` and `HE_centrality`
2. `CEC` and `HEC`
3. `clique_eigenvector_centrality` and `H_eigenvector_centrality`
4. `CM_eigenvector_centrality` and `H_eigenvector_centrality`

I don't like 2, not explicit enough. 3 and 4 make it explicit that they are centralities of the type "eigenvector".
I would maybe go with 3 but no strong opinion. 1 and 4 are good with me too.

**Comment by iaciac** [comment]
I would go for (3) in the spirit of keeping it as informative as possible. The others are good as well, probably I would just avoid the (2).

**Comment by leotrs** [comment]
I'd suggest we shorten `centrality` to `cent`.
