### ISSUE TITLE
Same edge (by members) gets multiple IDs in erdos_renyi_hypergraph

### ISSUE THREAD

**Issue by maximelucas** [ComplexGroupInteractions/xgi#34]
Working on #29 to remove singletons, I came across this:
Running 
```python
import xgi
n = 10
m = 50
p = 0.1
H = xgi.erdos_renyi_hypergraph(n, m, p)
```
then in `H._edge`, a given edge sometimes appear more than once with different IDs, e.g. `{ 38: [9],  39: [9],  48: [9], ...}`.

In addition, not all nodes are present in edges as a singleton. For example, there is a node 8 but no singleton edge [8].

Haven't checked if #33 fixes this?

**Comment by nwlandry** [comment]
The hypergraph class currently supports self-loops and multi-edges. I would be fine with eliminating these artifacts, but as of right now, it works as I would expect, though maybe not desirable. Happy for any suggestions.

**Comment by leotrs** [comment]
If @maximelucas agrees, please close this issue :)
