### ISSUE TITLE
Interface of NodeView

### ISSUE THREAD

**Issue by leotrs** [ComplexGroupInteractions/xgi#40]
`NodeView` supports accessing the edge ids that contain a node in three different ways:
```python
H = some_hypergraph()
H.nodes[1] == H.nodes(1) == H.members(1)
# -> True
```
I find this unpythonic. I'd much rather there was a single way of doing things if at all possible. If there was exactly one way of accessing the edges that contain a node, *which would you prefer?* If anyone can argue that we should support two (or more) ways of doing the same thing, I'm all ears.

Related to #20.

**Comment by leotrs** [comment]
cc @nwlandry

**Comment by nwlandry** [comment]
That makes sense to me. If I had to pick one of them, I would say that `H.nodes[n]` makes most sense to me and then we can delete the `members()` method and repurpose the call method. What are your thoughts on that?

**Comment by lordgrilo** [comment]
Symmetrically, H.members(edge_id) could return the node_ids of the nodes in the edge? Is this covered already by EdgeViews? 😕 😨

**Comment by leotrs** [comment]
I agree that `H[1]` should return the attributes. I like the suggestion of membership/members.

**Comment by nwlandry** [comment]
Okay, just to organize this discussion a bit more:

Here are the attributes that can be assigned:
1. The Hypergraph class
    a. the `__item__` property called as `H[id]`
    b. the `__call__` property called as `H(id)` (Currently unused)

Note that now H.nodes and H.edge_ids are essentially the same base class (IDView) with a thin wrapper around them.

2. The IDView class
    a. the `__item__` property called as, for instance, `H.nodes[id]`
    b. the `__call__` property called as, for instance, `H.edge_ids(id)`
    c. the `members()` method called as, for instance, `H.nodes.members(id)`

3. The EdgeView class
    a. the `__item__` property called as, for instance, `H.edges[item]`
    b. the `__call__` property called as, for instance, `H.edges(item)`

From what I'm hearing, the proposal is the following:
* Have 1a and 2a return attributes, not neighbors
* Have 2c return the bipartite neighbors
* Potentially rename 2c
* Use 2b for something else

Another point was that `H.edge_ids[id]` returns the same thing as `H.edges[id converted to sequential order]`

**Comment by nwlandry** [comment]
Right now, `H.edge_ids` returns what `H.edges` used to, i.e., edges associated with IDs in an adjacency dict. `H.edges` returns an edge list without associated IDs, as per the discussion in #28. Hope that clarifies.

**Comment by nwlandry** [comment]
With regards to the list above, I agree with bullet point 1, but with regards to the remaining bullet points, I potentially think that 2b can be used for the bipartite neighbors unless someone can think of another use for it.

**Comment by leotrs** [comment]
I personally dislike the way that NetworkX uses notation such as `G[]` and `G.nodes()`. My general proposal is that, as much as possible, there should be one and only one way of accessing a piece of information.

As far as I can tell, there are four different types of things I may want to access: attributes, neighbors, members, or ids. So here is what I propose:

```python
H = some_hypergraph()

# bracket notation to access hypergraph attributes
H["name"]
# -> "my favorite hypergraph"

# properties to access nodes, edges, and ids
H.nodes
# -> [1, 2, 3, "foo", object(), ...]
H.edges
# -> [{1, 2}, {"foo", 3, 1}, {2, 1}, ...]
H.edge_ids
# -> {1: {1, 2}, 8: {"foo", 3, 1}, 13: {2, 1}, ...}

# H.nodes and H.edges are View objects that support access to attributes
H.nodes[2]
# -> {"attr1": val1, "attr2": val2}
H.edges[8]
# -> {"attr3": val3, "attr4": val4}
H.edge_ids[8]
# same as H.edges[8]

# separate methods to access members
H.membership(3)
# -> {"foo", 3, 1}
H.members(8)
# -> {1, 2}
```

**Comment by nwlandry** [comment]
* I agree about only accessing a piece of information in one way.
* I like the brackets accessing hypergraph attributes.
* I think that if we go the route of member/membership, we should not pass in the bipartite neighbors (i.e., `H._edge` and `H._node`) into the view classes. So both `H.nodes` and `H.edges` would accept `H._node_attr` and `H._edge_attr` respectively and
```H.edge_ids
# ->[1, 8, 13, ...]
```
I say this because if the bipartite neighbors are handled with the `members()` function, then there's no need to pass the bipartite relationships into the EdgeIDView.
* I'm warming to the idea of the members/membership function in the hypergraph class - could even be more efficient!
* For the `neighbors()` function, perhaps we have a flag that specifies whether they are edge or node neighbors?
* I noticed that in your example @leotrs that the output of `neighbors()` (for example) is a set. Currently H._edge stores the bipartite relations as a dictionary of lists, so were you picturing casting to a set?
*

**Comment by leotrs** [comment]
I agree we should keep the views as separate as possible.

> For the neighbors() function, perhaps we have a flag that specifies whether they are edge or node neighbors?

This would only be necessary if the edge ids and the node ids overlap. If they don't overlap, then there is no ambiguity.

> I noticed that in your example @leotrs that the output of neighbors() (for example) is a set. Currently H._edge stores the bipartite relations as a dictionary of lists, so were you picturing casting to a set?

No, don't mind me, I shouldn't have used sets there...

**Comment by nwlandry** [comment]
In many cases the edge ids and the node ids do overlap currently, but I suppose that we could enforce this.

**Comment by leotrs** [comment]
I think we should enforce that since the underlying structure is essentially a bipartite graph where the node ids should be unique.

**Comment by nwlandry** [comment]
I don't really see a problem with an edge with an ID of 0 and a node with an ID of 0 so long as a user specifies whether they are looking for a node or an edge. I think that one of the most time-consuming parts would be that every time a user adds an entity (node or edge) its ID must be checked to make sure it's unique. And in the case of neighbors(), I agree that it would be really nice to simply enter an ID. But (unless I'm thinking about it wrong) it would be a bit more complicated to do that and I wonder if there are cases where a user enters an edge ID that doesn't exist but instead it returns a node ID that does and its node neighbors.

**Comment by leotrs** [comment]
> I don't really see a problem with an edge with an ID of 0 and a node with an ID of 0 so long as a user specifies whether they are looking for a node or an edge.

In the latter case, then (id_number, "node") or (id_number, "edge") becomes the unique ID of each object ;) That means that we are always assigning a unique ID to each object. And if we are, then we might as well make that explicit and enforce it.

> every time a user adds an entity (node or edge) its ID must be checked to make sure it's unique.

The way NetworkX handles this is that if you add a node that already exists, it just won't do anything. So there's no need to check every time.

> And in the case of neighbors(), I agree that it would be really nice to simply enter an ID. But (unless I'm thinking about it wrong) it would be a bit more complicated to do that

Can you give an example of when this would be a problem? (In the case when we enforce unique IDs across nodes/edges).

> a user enters an edge ID that doesn't exist but instead it returns a node ID that does and its node neighbors.

This is precisely what can be prevented by enforcing unique IDs.

**Comment by nwlandry** [comment]
Gotcha. It seems as though our approaches are similar, e.g., given an edge with ID 0, you propose making that id a tuple (0, "edge") and to find its neighbors, you call
`H.neighbors((0, "edge"))`
and in the case I proposed, it would be
`H.neighbors(0, edge=True)`

I'm open to the approach that you describe (I do prefer the second option) so perhaps you could create a prototype of what you were thinking?

**Comment by leotrs** [comment]
That's not what I'm proposing! I'm sorry I think we are talking a bit past each other here so maybe we should clarify in in real-time.

FWIW, I am saying that your proposal `(0, edge=True)` is functionally the same as assigning the edge a tuple ID of `(0, "edge")`. Either way, the nodes and edges would have unique IDs. My main point is that **actually, explicitly** enforcing unique IDs for everything (e.g. by using the tuple IDs or by assigning unique numbers across nodes and edges) is better than doing it implicitly (e.g. by passing "edge" to some functions).

**Comment by maximelucas** [comment]
Okay, I caught up on the discussion! 
Overall, I like the proposition written down in Leo's longer message (starting with "I personally dislike the way that NetworkX uses notation such as".)

> This would only be necessary if the edge ids and the node ids overlap. If they don't overlap, then there is no ambiguity.
> 
> >
True, but the user might get confused anyway. If the names of the nodes and edges are explicit ("Alice", "Bob", "Alice-Bob"), there is no confusion in either case. But if the names are random integers (as in the random hypergraph generators) the user might get confused anyway even if the IDs are unique ("Wait, was 8 a node or an edge again?"). In that sense, specifying something like `edge=True` might be helpful in any case, and could even help the user by throwing an error if the input idea is not and edge/node. 

When looking for neighbors in hypergraph, there are 3 parameters I believe we mentioned so far: 
- neighbors of *who* : are we looking for the (edge) neighbors of an edge, or the (edge or node) neighbors of a node? Potential values: `{'edge', 'node'}`
- *format* of output: if looking for the neighbors of an edge, do we want them as a flat list of nodes or or as list of list of nodes (grouped by edges).
- *order* of neighbors: do we want to look for neighbors only at a certain order, say only in triangles? 

If we want to have a single function for all that, it would be nice an general, but maybe too general to be easy to use?

**Comment by leotrs** [comment]
> True, but the user might get confused anyway. If the names of the nodes and edges are explicit ("Alice", "Bob", "Alice-Bob"), there is no confusion in either case. But if the names are random integers (as in the random hypergraph generators) the user might get confused anyway even if the IDs are unique ("Wait, was 8 a node or an edge again?"). In that sense, specifying something like `edge=True` might be helpful in any case, and could even help the user by throwing an error if the input idea is not and edge/node.

This is a good point, perhaps the tuple ID is the best way to go. And in this case, `(0, edge=True)` could be a synonym of `(0, "edge")`. I insist on this because I do believe that if we are going to use unique IDs, the implementation should explicitly reflect that.

**Comment by leotrs** [comment]
In [this comment](https://github.com/ComplexGroupInteractions/xgi/issues/40#issuecomment-1019332276), I mentioned the `neighbors` function and sort of got off track so I want to get this issue back on track to the original question. The original intent was to determine a single way of accessing node data.

It seems like we have all agreed to go with what I propose in [this comment](https://github.com/ComplexGroupInteractions/xgi/issues/40#issuecomment-1019332276) (minus the last line in the code block which mentions the `neighbors` function). So let's do that. I'll make sure to go over the codebase and make sure to implement that. PR coming soon!
