### ISSUE TITLE
module 'xgi' has no attribute '__version__'

### ISSUE THREAD

**Issue by maximelucas** [ComplexGroupInteractions/xgi#43]
```python
import xgi
xgi.__version__
```
yields `module 'xgi' has no attribute '__version__'`. It would be nice to support it.

**Comment by leotrs** [comment]
That's a good point. There are two main ways to support version variables: hard-code them or make them increase automatically. The latter option is surprisingly hard because of how python packages work so I vote we hard code them.

However, this adds an item to the release check list...

**Comment by nwlandry** [comment]
This is a good idea! My thought is that we can add this code block (suggested in [this thread](https://stackoverflow.com/questions/2058802/how-can-i-get-the-version-defined-in-setup-py-setuptools-in-my-package)) in __init__.py at the top level which will get the version specified in setuptools:

```
import pkg_resources
__version__ = pkg_resources.require("xgi")[0].version
```

I just tested it locally and verified that it works.

**Comment by maximelucas** [comment]
Nice, fine with me.

**Comment by iaciac** [comment]
Good call! And good to know about this ;)
