### ISSUE TITLE
Add random seed option in the random hypergraph generators

### ISSUE THREAD

**Issue by maximelucas** [ComplexGroupInteractions/xgi#47]
For reproducibility, it would be nice to have a "random_seed" argument that can be set in the generators.

**Comment by iaciac** [comment]
We could do the same as in networkx right? https://networkx.org/documentation/stable/reference/randomness.html#randomness

**Comment by maximelucas** [comment]
Yea agreed. It seems they use this decorator `@py_random_state(2)` and generate a random number with `seed.random()`.
The decorator is implemented here: https://github.com/networkx/networkx/blob/main/networkx/utils/decorators.py.

**Comment by leotrs** [comment]
@maximelucas if #56 fully resolved this issue please close it :)
