### ISSUE TITLE
order, shape, number_of_edges, number_of_nodes

### ISSUE THREAD

**Issue by leotrs** [ComplexGroupInteractions/xgi#49]
All these functions do very similar things. In keeping with the idea of doing things only once, I vote we simplify them somehow.

I personally lean toward the nuclear option and just keeping `shape`. All the others are not necessary...

**Comment by maximelucas** [comment]
Agree with Nicholas

**Comment by iaciac** [comment]
Same, I would keep the two self-explanatory ones, since ```shape``` is not super intuitive to me. ```order()``` was there just because of networkx, but I agree is redundant at this point.

**Comment by leotrs** [comment]
I dislike `number_of_*` because they're too long for what they're trying to achieve. Usually you'll see the code
```python
N = H.number_of_nodes()
M = H.number_of_edges()
```
and the following code is riddled with `N` and `M`, which is not super readable I think, and at that point I'd rather even do something like `H.N` and `H.M` instead. But I understand that these are just my opinionated positions... so I won't push back since the three of you prefer `number_of_*` already.

**Comment by leotrs** [comment]
Another relevant question is what should `len(H)` return? Currently it returns the number of nodes and there is no short way of getting the number of edges (the long form is to execute `H.number_of_edges()`.

Am I over thinking this?

**Comment by nwlandry** [comment]
What if we rename the methods to `num_nodes` and `num_edges` and make them properties? That would cut down the number of characters from 17 to 9.

**Comment by leotrs** [comment]
I think that's a good compromise
