### ISSUE TITLE
sparse matrix warning in adjacency_matrix()

### ISSUE THREAD

**Issue by maximelucas** [ComplexGroupInteractions/xgi#58]
Calling
```python       
import xgi
H = xgi.random_hypergraph(10, [0.1, 0.01])
A = xgi.adjacency_matrix(H, weighted=True)
```
yields two warnings:
```python
/usr/local/lib/python3.9/site-packages/scipy/sparse/compressed.py:291: SparseEfficiencyWarning: 
Comparing a sparse matrix with a scalar greater than zero using < is inefficient, try using >= instead. 
  warn(bad_scalar_msg, SparseEfficiencyWarning)
/usr/local/lib/python3.9/site-packages/scipy/sparse/_index.py:125: SparseEfficiencyWarning: 
Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)
```
When `weighted=False`, I cannot reproduce a warning (but I might have had one in the past, unsure).
It seems to come from the last line in 
```python
if not weighted:
    A = (A >= s) * 1
else:
    A[A < s] = 0
```

**Comment by maximelucas** [comment]
Related: scipy is moving away from sparse matrices apparently:
https://docs.scipy.org/doc/scipy/reference/sparse.html
"This package is switching to an array interface, compatible with NumPy arrays, from the older matrix interface. We recommend that you use the array objects (bsr_array, coo_array, etc.) for all new work."

**Comment by nwlandry** [comment]
Scipy 1.8.0 is (as far as I could tell) the first version of Scipy that supports the array interface (it also is the most recent release). Currently, we don't allow v1.8.0 in the [default.txt](https://github.com/ComplexGroupInteractions/xgi/blob/main/requirements/default.txt) requirements file. So I'm in favor of eventually implementing this, but putting this on hold for a while.

**Comment by leotrs** [comment]
This has been fixed.
