### ISSUE TITLE
adjacency_matrix error when no edges (of order d)

### ISSUE THREAD

**Issue by maximelucas** [ComplexGroupInteractions/xgi#61]
Running 
```python
import xgi
H = xgi.Hypergraph()
H.add_edges_from([[0, 1, 2], [1, 2, 3], [2, 3, 4]]) #edgelist6

A, node_dict = xgi.adjacency_matrix(H, order=1, index=True)
```
returns
```
File ~/Dropbox (ISI Foundation)/WORK/SCIENCE/xgi/xgi/linalg/matrix.py:136, in adjacency_matrix(H, order, s, weighted, index)
    133     I = incidence_matrix(H, index=False, order=order)
    135 A = I.dot(I.T)
--> 136 A.setdiag(0)
    138 if not weighted:
    139     A = (A >= s) * 1

AttributeError: 'numpy.float64' object has no attribute 'setdiag'
```

That happens because, there is no edge of order 1 in the hypergraph. In that case, right now, we have
```python 
xgi.incidence_matrix(H, order=1, index=True)
# array([0])
```
so that `I.dot(I.T) == 0` which is an int which has no diagonal to set. 

To fix this, two options:
1. raise an error in incidence_matrix when there is no edge or no nodes, instead of returning [0].
2. have a `if else` in `adjacency_matrix` to return an NxN array of zeros if `I == [0]`. Probably need to add `sparse` argument there too then to deal with both cases coming from `incidence_matrix`.

What do you think? Do we want to return [0] for the incidence matrix when there are no edges/nodes or not?

**Comment by leotrs** [comment]
It seems to me that in this case `xgi.incidence_matrix(H, order=1, index=True)` should return an empty array because there are no columns (or rows?) in this matrix. AND THEN, `xgi.adjacency_matrix` should have a conditional to check if this array is empty.

**Comment by iaciac** [comment]
Agree, I would go for the [] as well
