### ISSUE TITLE
Normalize edge "order" and "size"

### ISSUE THREAD

**Issue by leotrs** [ComplexGroupInteractions/xgi#67]
The words "order" and "size" are used throughout the codebase to refer to the number of nodes in an edge (where order = size-1). I'd suggest we choose one and remove all instances of the other. For example, we have `H.edge_size` but `H.edges_of_order`.

**Comment by leotrs** [comment]
FWIW, I'd rather keep order so that we don't have problems when implementing simplicial complexes.

**Comment by iaciac** [comment]
I'm more than OK with order!

**Comment by maximelucas** [comment]
Good point. I'm fine with order too.

**Comment by nwlandry** [comment]
I'm okay with doing this, but will admit that this will be a bit of habit for me to break :). Along these lines, is the biggest remaining change the `IDDegreeView` class?

**Comment by nwlandry** [comment]
One thing that probably will need to change is that we may not be able to effectively use `IDDegreeView` class as a base class if we choose to use `edge_order` instead of `edge_size`, because degree and edge order will be off by one from each other.

**Comment by leotrs** [comment]
Oh jeez that complicates things.

**Comment by leotrs** [comment]
Related to #82

**Comment by nwlandry** [comment]
This was fixed with EdgeStats, no?

**Comment by leotrs** [comment]
Kind of. We now have both order and size, so any EdgeStat (or any other part of the codebase that is aware of the stats package) can choose which one to use. So on that front we are fine.

What has not been addressed is the fact that currently, `SimplicialComplex` inherits from `Hypergraph` and that is Very Messy And Bad.
