### ISSUE TITLE
`remove_simplex_ids_from` does not enforce removing subfaces

### ISSUE THREAD

**Issue by nwlandry** [ComplexGroupInteractions/xgi#85]
`remove_simplex_id` enforces removing all subfaces as well and calls `remove_simplex_ids_from` to do so. Because of this, `remove_simplex_ids_from` does not enforce simpliciality. I think that `remove_simplex_ids_from` should call `remove_simplex_id` and either
1. Implement the contents of `remove_simplex_ids_from` directly in `remove_simplex_id`
2. rename `remove_simplex_ids_from` to be a helper function.

so that calling `remove_simplex_id` in  `remove_simplex_ids_from` is not circular.

**Comment by maximelucas** [comment]
fixed in #247
