### ISSUE TITLE
Implement method that returns nodes with the same memberships

### ISSUE THREAD

**Issue by leotrs** [ComplexGroupInteractions/xgi#93]
Analogous to `duplicate_edges`, which returns edges with the same members

**Comment by nwlandry** [comment]
Perhaps `collapse_duplicate_elements` in [HyperNetX](https://github.com/pnnl/HyperNetX/blob/master/hypernetx/classes/entity.py) would be helpful.

**Comment by leotrs** [comment]
This is implemented in #150 as `IDView.lookup`.
