### ISSUE TITLE
The current "egonet" method is wrong

### ISSUE THREAD

**Issue by leotrs** [ComplexGroupInteractions/xgi#98]
The current method returns all edges a node belongs to. This is not called the egonet, it should be called something else. The egonet includes edges among nodes that are neighbors of the specified node.

**Comment by nwlandry** [comment]
What if we call this `edge_neighborhood`? or something like that?

I think a way that one could get the `egonet` might be something like `xgi.subhypergraph(H, H.neighbors(n) + {n})`

**Comment by leotrs** [comment]
I think what the current egonet does can simply be retrieved by `H.nodes.memberships(n)`? So no need to call it something else I think.

> I think a way that one could get the egonet might be something like xgi.subhypergraph(H, H.neighbors(n) + {n})

This seems reasonable! Sometimes the egonet of `n` contains `n` and sometimes it doesn't, so the `+{n}` at the end should be conditional on some user-supplied parameter.
